name: 🐛 Bug Report
description: Report a reproducible or regression bug.
labels: ["Needs: Triage :mag:"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of what the bug is. Include screenshots if needed. Test using the [latest react-native-system-navigation-bar release](https://github.com/kadiraydinli/react-native-system-navigation-bar/releases/latest) to make sure your issue has not already been fixed.
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: react-native-system-navigation-bar version
      description: What is the latest version of react-native-system-navigation-bar that this issue reproduces on? Please only list the highest version you tested.
      placeholder: ex. 2.5.0
    validations:
      required: true
  - type: input
    id: react-native-version
    attributes:
      label: React Native version
      description: What is the latest version of react-native that this issue reproduces on? Please only list the highest version you tested.
      placeholder: ex. 0.71.0
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Snack, code example, screenshot, or link to a repository
      description: |
        Please provide a Snack (https://snack.expo.dev/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
        You may provide a screenshot of the application if you think it is relevant to your bug report.
    validations:
      required: false